service: aws-node-express-dynamodb-api-project
frameworkVersion: '3'

plugins:
  - serverless-newrelic-lambda-layers

custom:
  tableName: 'users-table-${sls:stage}'
  newRelic:
    accountId: <NR account ID>
    apiKey: <NR user api key>
    linkedAccount: <NR account ID>

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  iam:
    role:
      name: aws-express-api-${sls:stage}-${aws:region}-lambdaRole
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true
    NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
